"use client"
import Navbar from "./components/Navegation";
import "./globals.css";
import { usePathname } from "next/navigation";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Contract",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();
  const isDashboard = pathname?.startsWith('/dashboard');
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        {/* Comprueba si la ruta actual es parte del dashboard */}
        {!isDashboard && <Navbar />}
        {children}
      </body>
    </html>
  );
}